export const categoriesMap: { [key: number]: string } = {
  1: "Alcantarilla",
  2: "Animales",
  3: "Bacheo",
  4: "Banqueta",
  5: "Basura",
  6: "Cables",
  7: "Denuncia",
  8: "Fuga",
  9: "Graffiti",
  10: "Luminaria",
  11: "Poda",
  12: "Registro",
  13: "Vehículo Abandonado",
};

export const subcategoriesMap: { [key: number]: string } = {
  1: "Desnivelada",
  2: "Faltante",
  3: "Rota",
  4: "Tapada",
  5: "Cadáver",
  6: "Maltrato",
  7: "Chico",
  8: "Mediano",
  9: "Grande",
  10: "Socavón",
  11: "Dañada",
  12: "Inexistente",
  13: "Bolsa",
  14: "Suelta",
  15: "Tiliche",
  16: "Acumulación",
  17: "Colgante",
  18: "General",
  19: "Obstáculo",
  20: "Olor",
  21: "Ruido",
  22: "Agua",
  23: "Drenaje",
  24: "Único",
  25: "Múltiples",
};

export const prioritiesMap: { [key: number]: string } = {
  1: "Regular",
  2: "Urgente",
  3: "VIP",
};